package factorizacioncholesky;

import javax.swing.JOptionPane;

/**
 *
 * @author Carlos, Diego y Daniel
 */
public class Visual extends javax.swing.JFrame {

    /**
     * Creates new form Visual
     */
    public Visual() {
        initComponents();
        setLocationRelativeTo(null);
        jDialogFactorizacion.setLocationRelativeTo(null);
        jDialogResolverSistema.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogFactorizacion = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableMatrizC = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTableMatrizCTraspuesta = new javax.swing.JTable();
        jButtonCerrarFactChol = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jDialogResolverSistema = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableSolucionSistema = new javax.swing.JTable();
        jButtonCerrarResSist = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldElementos = new javax.swing.JTextField();
        jButtonCrearMatriz = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMatriz = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableTerminosIndependientes = new javax.swing.JTable();
        jButtonIngresar = new javax.swing.JButton();
        jButtonCalcFact = new javax.swing.JButton();
        jButtonResolverSist = new javax.swing.JButton();
        jButtonLimpiar = new javax.swing.JButton();

        jDialogFactorizacion.setTitle("Factorización de Cholesky");
        jDialogFactorizacion.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-math-25.png")).getImage());
        jDialogFactorizacion.setModal(true);
        jDialogFactorizacion.setResizable(false);

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));

        jTableMatrizC.setBackground(new java.awt.Color(204, 204, 204));
        jTableMatrizC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTableMatrizC.setFont(new java.awt.Font("MathJax_Typewriter", 0, 15)); // NOI18N
        jTableMatrizC.setForeground(new java.awt.Color(0, 0, 0));
        jTableMatrizC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "", "", "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableMatrizC.setEnabled(false);
        jTableMatrizC.setGridColor(new java.awt.Color(0, 0, 0));
        jScrollPane5.setViewportView(jTableMatrizC);

        jTableMatrizCTraspuesta.setBackground(new java.awt.Color(204, 204, 204));
        jTableMatrizCTraspuesta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTableMatrizCTraspuesta.setFont(new java.awt.Font("MathJax_Typewriter", 0, 15)); // NOI18N
        jTableMatrizCTraspuesta.setForeground(new java.awt.Color(0, 0, 0));
        jTableMatrizCTraspuesta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "", "", "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableMatrizCTraspuesta.setEnabled(false);
        jTableMatrizCTraspuesta.setGridColor(new java.awt.Color(0, 0, 0));
        jScrollPane6.setViewportView(jTableMatrizCTraspuesta);

        jButtonCerrarFactChol.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCerrarFactChol.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButtonCerrarFactChol.setForeground(new java.awt.Color(0, 0, 0));
        jButtonCerrarFactChol.setText("Cerrar");
        jButtonCerrarFactChol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarFactCholActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("L");

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("L'");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonCerrarFactChol))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jButtonCerrarFactChol)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialogFactorizacionLayout = new javax.swing.GroupLayout(jDialogFactorizacion.getContentPane());
        jDialogFactorizacion.getContentPane().setLayout(jDialogFactorizacionLayout);
        jDialogFactorizacionLayout.setHorizontalGroup(
            jDialogFactorizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jDialogFactorizacionLayout.setVerticalGroup(
            jDialogFactorizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jDialogResolverSistema.setTitle("Solución");
        jDialogResolverSistema.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-math-25.png")).getImage());
        jDialogResolverSistema.setModal(true);
        jDialogResolverSistema.setResizable(false);

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));

        jTableSolucionSistema.setBackground(new java.awt.Color(204, 204, 204));
        jTableSolucionSistema.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTableSolucionSistema.setFont(new java.awt.Font("MathJax_Typewriter", 0, 15)); // NOI18N
        jTableSolucionSistema.setForeground(new java.awt.Color(0, 0, 0));
        jTableSolucionSistema.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableSolucionSistema.setToolTipText("Solución al sistema Mx=b");
        jTableSolucionSistema.setEnabled(false);
        jTableSolucionSistema.setGridColor(new java.awt.Color(0, 0, 0));
        jScrollPane3.setViewportView(jTableSolucionSistema);

        jButtonCerrarResSist.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCerrarResSist.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jButtonCerrarResSist.setForeground(new java.awt.Color(0, 0, 0));
        jButtonCerrarResSist.setText("Cerrar");
        jButtonCerrarResSist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarResSistActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jButtonCerrarResSist))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonCerrarResSist)
                .addGap(13, 13, 13))
        );

        javax.swing.GroupLayout jDialogResolverSistemaLayout = new javax.swing.GroupLayout(jDialogResolverSistema.getContentPane());
        jDialogResolverSistema.getContentPane().setLayout(jDialogResolverSistemaLayout);
        jDialogResolverSistemaLayout.setHorizontalGroup(
            jDialogResolverSistemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialogResolverSistemaLayout.setVerticalGroup(
            jDialogResolverSistemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Factorización Cholesky");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-math-25.png")).getImage());
        setMaximumSize(new java.awt.Dimension(614, 610));
        setMinimumSize(new java.awt.Dimension(614, 610));
        setResizable(false);
        setSize(new java.awt.Dimension(614, 610));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setMaximumSize(new java.awt.Dimension(614, 588));
        jPanel1.setMinimumSize(new java.awt.Dimension(614, 588));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(614, 588));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Introduzca la cantidad de elementos de la matriz:");

        jTextFieldElementos.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldElementos.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jTextFieldElementos.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldElementos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldElementos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldElementosActionPerformed(evt);
            }
        });
        jTextFieldElementos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldElementosKeyTyped(evt);
            }
        });

        jButtonCrearMatriz.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCrearMatriz.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButtonCrearMatriz.setForeground(new java.awt.Color(0, 0, 0));
        jButtonCrearMatriz.setText("Crear");
        jButtonCrearMatriz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearMatrizActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setMaximumSize(new java.awt.Dimension(602, 460));
        jPanel2.setMinimumSize(new java.awt.Dimension(602, 460));
        jPanel2.setPreferredSize(new java.awt.Dimension(602, 460));

        jTableMatriz.setBackground(new java.awt.Color(204, 204, 204));
        jTableMatriz.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTableMatriz.setFont(new java.awt.Font("MathJax_Typewriter", 0, 15)); // NOI18N
        jTableMatriz.setForeground(new java.awt.Color(0, 0, 0));
        jTableMatriz.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "", "", "", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableMatriz.setToolTipText("Matriz");
        jTableMatriz.setGridColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(jTableMatriz);
        if (jTableMatriz.getColumnModel().getColumnCount() > 0) {
            jTableMatriz.getColumnModel().getColumn(0).setMinWidth(5);
            jTableMatriz.getColumnModel().getColumn(0).setPreferredWidth(5);
            jTableMatriz.getColumnModel().getColumn(0).setMaxWidth(5);
        }

        jTableTerminosIndependientes.setBackground(new java.awt.Color(204, 204, 204));
        jTableTerminosIndependientes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTableTerminosIndependientes.setFont(new java.awt.Font("MathJax_Typewriter", 0, 15)); // NOI18N
        jTableTerminosIndependientes.setForeground(new java.awt.Color(0, 0, 0));
        jTableTerminosIndependientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {""},
                {""},
                {""},
                {""}
            },
            new String [] {
                ""
            }
        ));
        jTableTerminosIndependientes.setToolTipText("Términos independientes");
        jTableTerminosIndependientes.setGridColor(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(jTableTerminosIndependientes);

        jButtonIngresar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonIngresar.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButtonIngresar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonIngresar.setText("Ingresar");
        jButtonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIngresarActionPerformed(evt);
            }
        });

        jButtonCalcFact.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCalcFact.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButtonCalcFact.setForeground(new java.awt.Color(0, 0, 0));
        jButtonCalcFact.setText("Calcular Factorización");
        jButtonCalcFact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcFactActionPerformed(evt);
            }
        });

        jButtonResolverSist.setBackground(new java.awt.Color(255, 255, 255));
        jButtonResolverSist.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButtonResolverSist.setForeground(new java.awt.Color(0, 0, 0));
        jButtonResolverSist.setText("Resolver Sistema");
        jButtonResolverSist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResolverSistActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonIngresar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCalcFact)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonResolverSist)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonIngresar)
                    .addComponent(jButtonCalcFact)
                    .addComponent(jButtonResolverSist)))
        );

        jButtonCalcFact.setVisible(false);
        jButtonResolverSist.setVisible(false);

        jButtonLimpiar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonLimpiar.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButtonLimpiar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonLimpiar.setText("Limpiar");
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(141, 141, 141)
                                .addComponent(jTextFieldElementos, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(69, 69, 69)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonCrearMatriz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jButtonCrearMatriz, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldElementos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        jPanel2.setVisible(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCrearMatrizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearMatrizActionPerformed
        try {
            int cant = Integer.parseInt(jTextFieldElementos.getText());
            if (cant > 0 && cant <= 30) {

                Object[][] obj = new Object[cant][cant];

                for (int i = 0; i < cant; i++) {
                    for (int j = 0; j < cant; j++) {
                        obj[i][j] = 0;
                    }
                }

                String[] s = new String[cant];
                Class[] c = new Class[cant];
                for (int i = 0; i < cant; i++) {
                    c[i] = java.lang.Double.class;
                }

                for (int i = 0; i < cant; i++) {
                    s[i] = "";
                }

                jTableMatriz.setModel(new javax.swing.table.DefaultTableModel(obj, s
                ) {

                    @Override
                    public Class getColumnClass(int columnIndex) {
                        return c[columnIndex];
                    }
                });
                Object[][] obj2 = new Object[cant][1];

                for (int i = 0; i < cant; i++) {
                    obj2[i][0] = 0;
                }

                String[] s2 = {""};
                jTableTerminosIndependientes.setModel(new javax.swing.table.DefaultTableModel(obj2, s2
                ) {
                    @Override
                    public Class getColumnClass(int columnIndex) {
                        return c[columnIndex];
                    }

                });

                jPanel2.setVisible(true);
                matriz = new double[cant][cant];
                b = new double[cant];

                jButtonCrearMatriz.setEnabled(false);

            } else {
                throw new NumberFormatException();
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(jPanel1, "El número debe ser mayor que 0 y menor o igual que 30.", "Advertencia", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButtonCrearMatrizActionPerformed

    private void jButtonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIngresarActionPerformed
        try {
            for (int i = 0; i < matriz.length; i++) {
                for (int j = 0; j < matriz.length; j++) {
                    Object o = jTableMatriz.getValueAt(i, j);
                    matriz[i][j] = Double.parseDouble(o.toString());
                }
            }

            for (int i = 0; i < b.length; i++) {
                Object o = jTableTerminosIndependientes.getValueAt(i, 0);
                b[i] = Double.parseDouble(o.toString());
            }
            jButtonCalcFact.setVisible(true);
            jButtonResolverSist.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(jPanel1, "Ingrese valores válidos.", "Advertencia", JOptionPane.INFORMATION_MESSAGE);

        }
    }//GEN-LAST:event_jButtonIngresarActionPerformed

    private void jButtonCalcFactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcFactActionPerformed
        if (TrabajoConMatrices.definidaPositiva(matriz)) {

            double[][] m1 = FactorizacionDeCholesky.factorizacionCholesky(matriz.length, matriz);
            double[][] m1Traspuesta = TrabajoConMatrices.traspuesta(m1);

            Object[][] obj1 = new Object[m1.length][m1.length];
            Object[][] obj2 = new Object[m1Traspuesta.length][m1Traspuesta.length];

            String[] s = new String[m1.length];
            for (int i = 0; i < s.length; i++) {
                s[i] = "";
            }

            Class[] c = new Class[m1.length];
            for (int i = 0; i < c.length; i++) {
                c[i] = java.lang.Double.class;
            }

            jTableMatrizC.setModel(new javax.swing.table.DefaultTableModel(
                    obj1,
                    s
            ) {
                Class[] types = c;

                @Override
                public Class getColumnClass(int columnIndex) {
                    return types[columnIndex];
                }

            });

            jTableMatrizCTraspuesta.setModel(new javax.swing.table.DefaultTableModel(
                    obj2,
                    s
            ) {
                Class[] types = c;

                @Override
                public Class getColumnClass(int columnIndex) {
                    return types[columnIndex];
                }
            });

            for (int i = 0; i < m1.length; i++) {
                for (int j = 0; j < m1.length; j++) {
                    jTableMatrizC.setValueAt(m1[i][j], i, j);
                }
            }

            for (int i = 0; i < m1Traspuesta.length; i++) {
                for (int j = 0; j < m1Traspuesta.length; j++) {
                    jTableMatrizCTraspuesta.setValueAt(m1Traspuesta[i][j], i, j);
                }
            }

            jDialogFactorizacion.pack();
            jDialogFactorizacion.setVisible(true);

        } else {

            JOptionPane.showMessageDialog(jPanel1, "La matriz incumple algunas de las condiciones para aplicar factorización de Cholesky", "Advertencia", JOptionPane.INFORMATION_MESSAGE);

        }


    }//GEN-LAST:event_jButtonCalcFactActionPerformed

    private void jButtonCerrarFactCholActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarFactCholActionPerformed
        jDialogFactorizacion.setVisible(false);
    }//GEN-LAST:event_jButtonCerrarFactCholActionPerformed

    private void jButtonResolverSistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResolverSistActionPerformed
        if (TrabajoConMatrices.definidaPositiva(matriz)) {
            double[] solucionSist = FactorizacionDeCholesky.resolverSistemaUsandoCholesky(matriz.length, matriz, b);
            Object[][] obj1 = new Object[solucionSist.length][2];
            jTableSolucionSistema.setModel(new javax.swing.table.DefaultTableModel(obj1, new String[]{"", ""}) {
                Class[] types = new Class[]{
                    java.lang.String.class, java.lang.Double.class
                };

                @Override
                public Class getColumnClass(int columnIndex) {
                    return types[columnIndex];
                }
            });
            for (int i = 0; i < solucionSist.length; i++) {
                jTableSolucionSistema.setValueAt("x".concat(String.valueOf(i + 1)), i, 0);
                jTableSolucionSistema.setValueAt(solucionSist[i], i, 1);
            }
            jDialogResolverSistema.pack();
            jDialogResolverSistema.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(jPanel1, "La matriz incumple algunas de las condiciones para aplicar factorizacion de Cholesky", "Advertencia", JOptionPane.INFORMATION_MESSAGE);

        }

    }//GEN-LAST:event_jButtonResolverSistActionPerformed

    private void jButtonCerrarResSistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarResSistActionPerformed
        jDialogResolverSistema.setVisible(false);
    }//GEN-LAST:event_jButtonCerrarResSistActionPerformed

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed
        jPanel2.setVisible(false);
        jButtonCalcFact.setVisible(false);
        jButtonResolverSist.setVisible(false);
        jTextFieldElementos.setText("");
        jButtonCrearMatriz.setEnabled(true);
    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    private void jTextFieldElementosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldElementosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldElementosActionPerformed

    private void jTextFieldElementosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldElementosKeyTyped
        try {
            if (!Character.isDigit(evt.getKeyChar()) && evt.getKeyChar() != 8) {
                throw new NumberFormatException();
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(jPanel1, "Por favor ingrese un número válido.", "Advertencia", JOptionPane.INFORMATION_MESSAGE);
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldElementosKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Visual().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCalcFact;
    private javax.swing.JButton jButtonCerrarFactChol;
    private javax.swing.JButton jButtonCerrarResSist;
    private javax.swing.JButton jButtonCrearMatriz;
    private javax.swing.JButton jButtonIngresar;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JButton jButtonResolverSist;
    private javax.swing.JDialog jDialogFactorizacion;
    private javax.swing.JDialog jDialogResolverSistema;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTableMatriz;
    private javax.swing.JTable jTableMatrizC;
    private javax.swing.JTable jTableMatrizCTraspuesta;
    private javax.swing.JTable jTableSolucionSistema;
    private javax.swing.JTable jTableTerminosIndependientes;
    private javax.swing.JTextField jTextFieldElementos;
    // End of variables declaration//GEN-END:variables

    private double[][] matriz;
    private double[] b;
}
